name: Model training with Live Metrics in Studio
on:
  pull_request:
jobs:
  train:
    runs-on: ubuntu-latest
    name: Train model and report results
    environment: Production
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup environment
        uses: ./.github/actions/setup_environment

      - name: Train model
        env:
          STUDIO_TOKEN: ${{ secrets.STUDIO_TOKEN }}
          STUDIO_ENDPOINT: ${{ vars.STUDIO_ENDPOINT }}
          DVCLIVE_LOGLEVEL: DEBUG
          DVC_STUDIO_CLIENT_LOGLEVEL: DEBUG
        run: dvc exp run

      - name: Report results
        env:
          # Required for CML: https://cml.dev/doc/self-hosted-runners?tab=GitHub#pat
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          dvc metrics diff main --show-md >> report.md
          npm exec -- cml comment create report.md
          npm exec -- cml pr --rebase "dvc.lock" "params.yaml" "dvclive"
